export default {
    'UPDATE_EXPERIMENT_API_STATUS': 'UPDATE_EXPERIMENT_API_STATUS',
    'UPDATE_EXPERIMENT': 'UPDATE_EXPERIMENT',


    'UPDATE_VARIATION_API_STATUS': 'UPDATE_VARIATION_API_STATUS',
    'UPDATE_VARIATION': 'UPDATE_VARIATION',
    'DELETE_VARIATION': 'DELETE_VARIATION'
};
