export default {
    'UPDATE_EXPERIMENT_API_STATUS': 'UPDATE_EXPERIMENT_API_STATUS',
    'UPDATE_EXPERIMENT': 'UPDATE_EXPERIMENT',


    'UPDATE_VARIATION_API_STATUS': 'UPDATE_VARIATION_API_STATUS',
    'UPDATE_VARIATION': 'UPDATE_VARIATION',
    'DELETE_VARIATION': 'DELETE_VARIATION',

    'UPDATE_STATS_API_STATUS': 'UPDATE_STATS_API_STATUS',
    'UPDATE_TIMELINE_API_STATUS': 'UPDATE_TIMELINE_API_STATUS',
    'UPDATE_VARIATION_EVENTS_MAPPING': 'UPDATE_VARIATION_EVENTS_MAPPING',
    'UPDATE_EXPERIMENT_TIMELINE_MAPPING': 'UPDATE_EXPERIMENT_TIMELINE_MAPPING'
};
