#!/usr/bin/env python

import sys

try:
    import configparser
except ImportError:
    import ConfigParser as configparser

config = configparser.ConfigParser()
config.read(sys.argv[1])

print(config.get(sys.argv[2], sys.argv[3]))
