#!/bin/bash
set -e

SRCDIR=$(dirname $(cd ${0%/*} 2>>/dev/null ; echo `pwd`/${0##*/})) 
PRJDIR=${SRCDIR}/..
DEMODIR=${SRCDIR}
SERVERDIR=${PRJDIR}/dashboard/server
CLIENTDIR=${PRJDIR}/dashboard/client
SDKDIR=${PRJDIR}/sdk
CONFIGFILE=${SRCDIR}/demo-config.ini
CONFIGREADER="${SRCDIR}/.read_ini ${CONFIGFILE}"

# Install dependencies ---------------------------

## Server dependencies
cd ${SERVERDIR}
npm install 

## Client dependencies
cd ${CLIENTDIR}
npm install

## SDK dependencies
cd ${SDKDIR}
npm install

## Demo dependencies
cd ${DEMODIR}
npm install

# Build ------------------------------------------

API_URL=`${CONFIGREADER} app api_url`

## Client
cd ${CLIENTDIR}
API_URL=${API_URL} npm run build
rm -r ${DEMODIR}/dist-dashboard
cp -R ${CLIENTDIR}/dist ${DEMODIR}/dist-dashboard
### TODO: set api url in the build directory

## Demo app
cd ${DEMODIR}
rm -rf dist-demo
cp -R app dist-demo
node_modules/.bin/browserify -t [ envify --API_URL ${API_URL} ] dist-demo/main.js -o dist-demo/bundle.js
rm dist-demo/main.js

## Server
MYSQL_HOST=`${CONFIGREADER} mysql host`
MYSQL_USER=`${CONFIGREADER} mysql user`
MYSQL_PASS=`${CONFIGREADER} mysql password`
MYSQL_DATABASE=`${CONFIGREADER} mysql database`

MYSQL_CMD="mysql -h ${MYSQL_HOST} -u ${MYSQL_USER} -p${MYSQL_PASS} ${MYSQL_DATABASE}" 

${MYSQL_CMD} -s -N -e "SELECT count(*) FROM experiments;" > /dev/null 2>&1

if  [[ $? -ne 0 ]]; then
    for DELTA in ${SERVERDIR}/db/mysql-*.sql; do
        ${MYSQL_CMD} < ${DELTA} || { echo "FAILED APPLYING DELTA ${DELTA}"; exit 1; }
    done
fi

# Run --------------------------------------------

NODE_EXEC="node"
NODE_VERSION=`node --version`
if [[ ${NODE_VERSION:0:2} == "v4" ]]; then
    NODE_EXEC="node --harmony"
fi

cp ${SERVERDIR}/src/config/config.ini ${SERVERDIR}/src/config/config.ini.bkp
cp ${DEMODIR}/demo-config.ini ${SERVERDIR}/src/config/config.ini

## Dashboard
cd ${DEMODIR}
$NODE_EXEC app.js

cp ${SERVERDIR}/src/config/config.ini.bkp ${SERVERDIR}/src/config/config.ini
rm ${SERVERDIR}/src/config/config.ini.bkp
