#!/bin/bash
set -e

SRCDIR=$(dirname $(cd ${0%/*} 2>>/dev/null ; echo `pwd`/${0##*/})) 
PRJDIR=${SRCDIR}/..
DEMODIR=${SRCDIR}
. ${PRJDIR}/.bin/util.sh

SDKDIR=${PRJDIR}/sdk
export CONFIG_PATH=${DEMODIR}/demo-config.ini
CONFIG_READER="${PRJDIR}/.bin/ini_reader ${CONFIG_PATH}"

# Do not build data processor module
export WITHOUT_DATAPROC=1
export WITH_DEMO=1

# Install dependencies ---------------------------

${PRJDIR}/.bin/dependencies.sh

# Build ------------------------------------------

${PRJDIR}/.bin/build.sh

# Database ---------------------------------------
echo "Setting up database"
cd ${DISTDIR}

MYSQL_HOST=`${CONFIG_READER} mysql host`
MYSQL_USER=`${CONFIG_READER} mysql user`
MYSQL_PASS=`${CONFIG_READER} mysql password`
MYSQL_DATABASE=`${CONFIG_READER} mysql database`

MYSQL_CMD="mysql -h ${MYSQL_HOST} -u ${MYSQL_USER} -p${MYSQL_PASS} ${MYSQL_DATABASE}" 

echo "Testing if schema was loaded"

if ! ${MYSQL_CMD} -s -N -e "SELECT count(*) FROM experiments;" > /dev/null 2>&1; then
    echo "Loading schema"
    ${MYSQL_CMD} < ${DISTDIR}/server/db/mysql_schema.sql \
        || { echo "FAILED APPLYING SCHEMA" && exit 1; }
    ${MYSQL_CMD} < ${DISTDIR}/demo/demo-data.sql \
        || { echo "FAILED INSERTING DATA" && exit 1; }
fi

# Run --------------------------------------------

export NODE_ENV=production

cd ${DISTDIR}/server
npm install

cd ${DISTDIR}/demo
npm install

NODE_EXEC="node"
NODE_VERSION=`node --version`
if [[ ${NODE_VERSION:0:2} == "v4" ]]; then
    NODE_EXEC="node --harmony"
fi

## Dashboard
cd ${DISTDIR}/demo
$NODE_EXEC app.js